name: Go

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: "1.21.3"

      - name: Get dependencies
        run: |
          go get -v -t -d ./...
          go install github.com/mitchellh/gox@latest

      - name: Build
        run: go build -v ./...

      - name: Test
        run: go test -v ./...

      - name: Get version
        id: version
        run: |
          echo ${{github.sha}} > version_sha.txt
          id=$(echo ${{github.sha}} | cut -c 1-7)
          date=$(date +%Y-%m-%d)
          echo "::set-output name=id::$date-$id"

      - name: Build artifacts
        run: gox -os "linux windows" -arch="amd64" -output="quickmock"

      - uses: actions/upload-artifact@v3
        with:
          name: Windows version
          path: quickmock.exe

      - uses: actions/upload-artifact@v3
        with:
          name: Linux version
          path: quickmock

      - name: Release
        id: release
        uses: softprops/action-gh-release@v1
        with:
          files: |
            quickmock
            quickmock.exe
            version_sha.txt
          tag_name: ${{steps.version.outputs.id}}
          body: |
            Release ${{steps.version.outputs.id}}
            ${{github.sha}}
            For Windows download quickmock.exe, for Linux download quickmock
          draft: false
          prerelease: false
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
