name: Go

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: "1.21.3"

      - name: Get dependencies
        run: |
          go get -v -t -d ./...
          go install github.com/mitchellh/gox@latest

      - name: Build
        run: |
          go build -v ./...
          echo ${{github.sha}} > version_sha.txt

      - name: Test
        run: go test -v ./...

      - name: Build artifacts
        run: gox -os "linux windows" -arch="amd64" -output="quickmock"

      - uses: actions/upload-artifact@v3
        with:
          name: Windows version
          path: quickmock.exe

      - uses: actions/upload-artifact@v3
        with:
          name: Linux version
          path: quickmock

      - name: Release
        id: release
        uses: softprops/action-gh-release@v1
        with:
          files: |
            quickmock
            quickmock.exe
            version_sha.txt
          tag_name: ${{github.sha}}
          body: |
            ${{github.sha}}
          draft: false
          prerelease: false
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
